Repository eclipse-jdt/eclipse.jdt.core, pull requests merged in 2023-09, with the labels that each got.

#1414 Remove Y-builds reference in pom.xml
  pom.xml
Labels: bug

#1415 Fix Javadoc formatting when do not put block tags on separate line set
  org.eclipse.jdt.core/formatter/org/eclipse/jdt/internal/formatter/CommentsPreparator.java
Labels: regression

#1453 Confusion about File.separatorChar() causes failure to load .eea on windows
  org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/NullAnnotationBatchCompilerTest.java
Labels: Windows, test
