Repository eclipse-jdt/eclipse.jdt.core, pull requests merged in 2023-01, with the labels that each got.

#634 Issue 556 - [20][pattern switch][preview] - Grammar changes
  org.eclipse.jdt.core.compiler.batch/.settings/.api_filters
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/core/compiler/IProblem.java
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/ast/CaseStatement.java
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/problem/ProblemReporter.java
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/problem/messages.properties
  org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/CompilerInvocationTests.java
  org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/SwitchPatternTest.java
  org.eclipse.jdt.core/.settings/.api_filters
Labels: java_20

#532 Use meta index for reference search
  org.eclipse.jdt.core/search/org/eclipse/jdt/core/search/SearchPattern.java
Labels: enhancement

#651 Allow template completion in lambda internal blocks
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/CompletionTests18.java
  org.eclipse.jdt.core/codeassist/org/eclipse/jdt/internal/codeassist/CompletionEngine.java
Labels: bug
