Repository eclipse-jdt/eclipse.jdt.core, pull requests merged in 2024-12, with the labels that each got.

#1503 Completion for unimported types doesn't work
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/CompletionTests18.java
  org.eclipse.jdt.core/codeassist/org/eclipse/jdt/internal/codeassist/CompletionEngine.java
  org.eclipse.jdt.core/codeassist/org/eclipse/jdt/internal/codeassist/MissingTypesGuesser.java
  org.eclipse.jdt.core/codeassist/org/eclipse/jdt/internal/codeassist/complete/CompletionOnMemberAccess.java
Labels: content assist

#3387 [Performance] Full build takes more time since 2024-09 (type inference)
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/BoundSet.java
Labels: performance

#3411 Guard lookup in BoundSet::allSuperPairsWithCommonGenericTypeRecursive
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/BoundSet.java
Labels: performance

#3417 Improve DeltaProcessor file change detection #3036
  org.eclipse.jdt.core.tests.builder/src/org/eclipse/jdt/core/tests/builder/BuildpathTests.java
  org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/DeltaProcessor.java
Labels: bug, test

#3425 batch compiler.util: writeToDisk use Files.write()
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/util/Util.java
Labels: performance

#3433 [performance] optimized ClasspathDirectory
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/batch/ClasspathDirectory.java
Labels: performance

#3423 Fix "Redundant superinterface" warning depends on Interface name
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/MethodVerifier.java
  org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/SuperTypeTest.java
Labels: bug

#3386 Improve performance in CharOperation
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/core/compiler/CharOperation.java
  org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/CharOperationTest.java
Labels: performance

#3404 Fix never-ending TestBug261722
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/JavaSearchBugsTests.java
Labels: test

#3472 JavaSearchBugsTests2: do not add jar to classpath before creating
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/JavaSearchBugsTests2.java
Labels: test

#3473 ASTConverterTest(s): do not use not existing jclMin1.8.jar
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/ConverterTestSetup.java
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/AbstractJavaModelTests.java
Labels: test

#3475 [performance] determineIfOnClasspath with last project used #3470
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/JavaModelTests.java
  org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaModelManager.java
Labels: performance

#3484 Prevent too long Marker messages, fixes #1269
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/JavaSearchScopeTests.java
  org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaProject.java
Labels: bug
