Repository eclipse-jdt/eclipse.jdt.core, pull requests merged in 2025-02, with the labels that each got.

#3670 Fix problem with escaped character in text block with continuation char
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/parser/Scanner.java
  org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/ScannerTest.java
Labels: bug, regression

#3685 Fix various indent issues in cleanups/quick fixes in unformatted file
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/rewrite/describing/ASTRewritingExpressionsTest.java
  org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteAnalyzer.java
  org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteFormatter.java
Labels: bug

#3692 Revert "Fix various indent issues in cleanups/quick fixes in unformat…
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/rewrite/describing/ASTRewritingExpressionsTest.java
  org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteAnalyzer.java
  org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteFormatter.java
Labels: bug

#3707 APT: Fix cancel build during annotation processing #3317
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/apt/dispatch/RoundDispatcher.java
  org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/BuildNotifier.java
Labels: bug

#3597 [performance] BoundSet: move properTypesByInferenceVariable before loop
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/BoundSet.java
Labels: performance

#3720 Revert APT progress report - fixes #3718
  org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/AbstractImageBuilder.java
  org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/builder/BuildNotifier.java
Labels: bug, regression
