Repository eclipse-jdt/eclipse.jdt.core, pull requests merged in 2025-01, with the labels that each got.

#3486 Indexer: improve logging for empty .class/.jar files
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/classfmt/ClassFileReader.java
  org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/indexing/AddJarFileToIndex.java
  org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/search/indexing/BinaryIndexer.java
Labels: test

#3523 [performance] faster JavaProject.CycleInfo#add
  org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/JavaProject.java
Labels: performance

#3526 improve JavaSearchScopeTests.testBug250211() cleanup performance
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/model/JavaSearchScopeTests.java
Labels: performance, test

#3521 Make StringLiteral.getLiteralValue thread safe
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/dom/ASTVisitorTest.java
  org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/CharacterLiteral.java
  org.eclipse.jdt.core/dom/org/eclipse/jdt/core/dom/StringLiteral.java
Labels: bug

#3561 Don't evaluate the same type twice when renaming a method
  org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/hierarchy/HierarchyResolver.java
Labels: performance

#3566 Fix insert of annotation to not change indent of following line
  org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteAnalyzer.java
  org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteFormatter.java
Labels: bug

#3581 Replace some colossal strings in the compiler tests
  org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/StackMapAttributeTest.java
  org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/XLargeTest.java
Labels: test

#3583 remove SourceMapper.anonymousClassName #1834
  org.eclipse.jdt.core/model/org/eclipse/jdt/internal/core/SourceMapper.java
Labels: performance

#3594 [performance] InferenceVariable.hashCode: avoid Mersenne prime# 3593
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/lookup/InferenceVariable.java
Labels: performance

#3598 Isolate access to CompletionEngine in InternalCompletionProposal
  org.eclipse.jdt.core/codeassist/org/eclipse/jdt/internal/codeassist/InternalCompletionProposal.java
Labels: content assist

#3620 Handle ClosedByInterruptException in JRTUtil#safeReadBytes only once
  org.eclipse.jdt.core.compiler.batch/src/org/eclipse/jdt/internal/compiler/util/JRTUtil.java
  org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/util/JrtUtilTest.java
Labels: bug

#3631 Fix rewrite of statement body to not add extraneous newline plus space
  org.eclipse.jdt.core.tests.model/src/org/eclipse/jdt/core/tests/rewrite/describing/ASTRewritingStatementsTest.java
  org.eclipse.jdt.core/dom/org/eclipse/jdt/internal/core/dom/rewrite/ASTRewriteAnalyzer.java
Labels: bug

#3647 [performance] DiskIndex: use BufferedOutputStream
  org.eclipse.jdt.core/search/org/eclipse/jdt/internal/core/index/DiskIndex.java
Labels: performance
